#include <iostream>
#include <csignal>
#include <cstring>
#include <unistd.h>
#include <fcntl.h>
#include "typedef.h"
#include <getopt.h>
#include <sstream>
#include <string>
#include <vector>
#include <cstdarg>
#include <cstdlib>
#include <cmath>
#include <stdarg.h>